steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/quickstart-image:tag1', '.' ]
- name: 'quickstart-image'
  entrypoint: npm
  args: ['install']
- name: 'quickstart-image'
  entrypoint: npm
  args: ['run', 'start']
images:
- 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/quickstart-image:tag1'