steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/raiden-image:bot', '.' ]
- name: node
  entrypoint: npm
  args: ['install']
# - name: node
#   entrypoint: npm
#   args: ['start']
images:
- 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/raiden-image:bot'